name: Dynamic Matrix
on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating Systems
        default: "windows-latest,ubuntu-latest"
        type: string
      nodeVersion:
        description: Node Version
        default: "14,15,16"
        type: string
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        id: split_inputs
        with:
          script: "return {os: context.payload.inputs.os.split(','), versions: context.payload.inputs.nodeVersion.split(',')}"
          result-encoding: json
    outputs:
      matrix: ${{ steps.split_inputs.outputs.result }}
  node-matrix:
    needs:
      - prepare-matrix
    strategy:
      matrix:
        os: ${{fromJson(needs.prepare-matrix.outputs.matrix.os)}}
        node-version: ${{fromJson(needs.prepare-matrix.outputs.versions)}}
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v