name: Dynamic Matrix
on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating Systems
        default: "windows-latest,ubuntu-latest"
        type: string
      node-version:
        description: Node Version
        default: "14,15,16"
        type: string
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Split string using cut
        id: split_cut
        run: |
          echo "matrix-os=[${{inputs.os}}]" >> $GITHUB_OUTPUT
          echo "matrix-node-versions=[${{inputs.node-version}}]" >> $GITHUB_OUTPUT
    outputs:
      matrix-os: ${{ steps.step1.outputs.matrix-os }}
      matrix-node-versions: ${{ steps.step2.outputs.matrix-node-versions }}
  node-matrix:
    needs:
      - prepare-matrix
    strategy:
      matrix:
        os: ${{fromJson(needs.prepare-matrix.outputs.matrix-os)}}
        node-version: ${{fromJson(needs.prepare-matrix.outputs.node-versions)}}
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v