name: first-wkf
on: 
  - push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-cmd
        run: echo "This is the first echo"
      - name: second-cmd
        run: echo "this is the second echo"
      - name: install-nodejs
        run: sudo apt install nodejs
  second-job:
    runs-on: ubuntu-latest
    needs:
      - first-job
    steps:
      - name: first-cmd
        run: echo "This is the second-job"

  third-job:
    runs-on: ubuntu-latest
    needs:
      - second-job
    steps:
      - name: first-cmd
        run: echo "This is the third-job"
  fourth-job:
    runs-on: ubuntu-latest
    needs:
      - first-job
      - second-job
    steps:
      - name: first-cmd
        run: echo "This is the fourth-job"


