name: first-wkf
runs-on: ubuntu-latest
on: 
  - push
    branches: 
      - main
jobs:
  - name: first-cmd
    run: echo "This is the first echo"
  - name: second-cmd
    run: echo "this is the second echo"
  - name: install-nodejs
    run: apt install nodejs

