name: first-wkf
on: 
  - push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-cmd
        run: echo "This is the first echo"
      - name: second-cmd
        run: echo "this is the second echo"
      - name: install-nodejs
        run: apt install nodejs

